### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sbernhard** [theforeman/smart_proxy_dhcp_bluecat#12]
Hi, 

do you plan to create a new release and build a package in foreman-packaging? I guess this should be pretty easy.  Let me know if we can help.

Best regards,
Bernhard

**Comment by m4c3** [comment]
Hi,
i can release a new version and upload it to rubygems. But packaging goes way over my knowledge - would be awesome if you could assist here 
bye Matthias

**Comment by sbernhard** [comment]
sure. As it was packaged once, the update should be easy. Just tell me when you are ready with rubygems. I will finish the packaging then.

**Comment by m4c3** [comment]
New Version is published

**Comment by sbernhard** [comment]
Thanks.
See https://github.com/theforeman/foreman-packaging/pull/6340
